WIP: hw: abstract nested paging (Alternative 2: more readable, doesn't work)
The initial SVM implementation (correctly) just used another standard
x86_64 page table for nested paging. The EPT implementation is for Intel
VMX only. Since we don't know the underlying virtualization technology
at compile time, we need to pick the correct page table implementation
at runtime. To do this, we first at a "HPT" page table implementation
using the same base implementation and (more importantly) allocator as
the EPT implementation.

This is my go at picking a Vm_page_table implementation at runtime with
a virtual class. It just doesn't work yet:

epos/base-hw/src/core/spec/x86_64/virtualization/vm_session_component.cc:158:16: error: invalid initialization of non-const reference of type ‘Board::Vm_page_table&’ from an rvalue of type ‘Core::Vm_session_component::Vm_session_component(Genode::Rpc_entrypoint&, Genode::Session::Resources, const Genode::Session::Label&, Genode::Session::Diag, Genode::Ram_allocator&, Genode::Region_map&, unsigned int, Core::Trace::Source_registry&)::<lambda()>’
  158 |         _table([&]() -> Board::Vm_page_table& {
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  159 |                 if (Hw::Virtualization_support::has_vmx())
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  160 |                         return *(new (cma()) Board::Vm_page_table_ept(_alloc_table()));
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  161 |                 else
      |                 ~~~~
  162 |                         return *(new (cma()) Board::Vm_page_table_hpt(_alloc_table()));
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  163 |                 }),

If I skip the lambda and statically pick one of the implementations, I
get:
/usr/local/genode/tool/23.05/bin/../lib/gcc/x86_64-pc-elf/12.3.0/../../../../x86_64-pc-elf/bin/ld: debug/core-hw-pc.a(vm_session_component.o):(.data.rel.ro._ZTIN5Board17Vm_page_table_eptE[_ZTIN5Board17Vm_page_table_eptE]+0x10): undefined reference to `typeinfo for Board::Vm_page_table'

Issue #5218